name: winreg-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      msvc2019TargetZip: clip-${{ github.ref_name }}-msvc2019.zip
    steps:
      - name: git clone elements
        run: git clone --branch v4.1.2 https://github.com/GiovanniDicanio/WinReg.git
      
#       - name: try aria2 
#         shell: cmd
#         run: aria2c "https://github.com/dirkarnez/serial-locate/releases/download/v1.0.0/serial-locate.exe" 
        
      - name: modify WinReg/WinReg.vcxproj 
        shell: cmd
        run: cd WinReg && dir
        
        
